spring:
  datasource:
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    #//10.10.14.13
    username: root

mybatis-plus:
  global-config:
    refresh-mapper: true    # mapper 热加载



