spring:
  datasource:
    password: root
    url: jdbc:mysql://10.10.14.13:3306/test?characterEncoding=utf8&useSSL=false
    username: root

mybatis-plus:
  global-config:
    refresh-mapper: true    # mapper 热加载



